{% set name = "neptune-client" %}
{% set package_name = "neptune_client" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ package_name }}-{{ version }}.tar.gz
  sha256: d6699c8f4368b6797cb52cd6e9ace8b5786bd7a8de1015df1e3b78d84058a1be

build:
  noarch: python
  number: 1
  entry_points:
    - neptune = neptune.new.cli.__main__:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - bravado >=11.0.0,<12.0.0
    - click >=7.0
    - future >=0.17.1
    - gitpython >=2.0.8
    - oauthlib >=2.1.0
    - packaging
    - pandas
    - pillow >=1.1.6
    - psutil
    - pyjwt
    - python >={{ python_min }}
    - requests >=2.20.0
    - requests-oauthlib >=1.0.0
    - six >=1.12.0
    - urllib3
    - websocket-client >=0.35.0
    - boto3 >=1.28.0
    - swagger-spec-validator >=2.7.4
    - jsonschema-with-format

test:
  imports:
    - neptune
    - neptune.legacy
    - neptune.management
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client
  doc_url: https://github.com/neptune-ai/neptune-client/blob/master/README.md
  dev_url: https://github.com/neptune-ai/neptune-client

extra:
  recipe-maintainers:
    - aniezurawski
    - HubertJaworski
    - pitercl
    - shnela
    - Raalsky
    - PatrykGala
