{% set name = "neptune-client" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neptune-ai/neptune-client/archive/{{ version }}.tar.gz
  sha256: f2e5fb61fe24332b2565df4c6b84505ca2be2fdfd7d99fde69e507766593dca2

build:
  noarch: python
  number: 0
  entry_points:
    - neptune = neptune_cli.main:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - bravado
    - bravado-core
    - click >=7.0
    - future >=0.17.1
    - gitpython >=2.0.8
    - py3nvml
    - oauthlib >=2.1.0
    - pandas
    - pillow >=1.1.6
    - pyjwt
    - python
    - requests >=2.20.0
    - requests-oauthlib >=1.0.0
    - six >=1.12.0
    - websocket-client >=0.35.0
    - packaging

test:
  imports:
    - neptune
    - neptune.internal
    - neptune.internal.backends
    - neptune.internal.channels
    - neptune.internal.execution
    - neptune.internal.hardware
    - neptune.internal.hardware.cgroup
    - neptune.internal.hardware.gauges
    - neptune.internal.hardware.gpu
    - neptune.internal.hardware.metrics
    - neptune.internal.hardware.metrics.reports
    - neptune.internal.hardware.metrics.service
    - neptune.internal.hardware.resources
    - neptune.internal.hardware.system
    - neptune.internal.notebooks
    - neptune.internal.storage
    - neptune.internal.streams
    - neptune.internal.threads
    - neptune.internal.utils
    - neptune.internal.websockets
    - tests.neptune
    - tests.neptune.internal
    - tests.neptune.internal.backends
    - tests.neptune.internal.channels
    - tests.neptune.internal.hardware
    - tests.neptune.internal.hardware.gauges
    - tests.neptune.internal.hardware.metrics
    - tests.neptune.internal.hardware.resources
    - tests.neptune.internal.storage
    - tests.neptune.utils

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client
  doc_url: https://github.com/neptune-ai/neptune-client/blob/master/README.md
  dev_url: https://github.com/neptune-ai/neptune-client

extra:
  recipe-maintainers:
    - szymon-kuklewicz
    - aniezurawski
    - hubertjaworskineptune
    - pitercl
