{% set name = "neptune-client" %}
{% set version = "0.16.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/raalsky-testing/neptune-client/archive/refs/tags/0.16.10.tar.gz
  sha256: c186145d7317bf818b9007a8d37d57d20e1fb5d945210d14205089c7169a88e9

build:
  noarch: python
  number: 1
  entry_points:
    - neptune = neptune_cli.main:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - bravado >=11.0.0,<12.0.0
    - click >=7.0
    - dataclasses >=0.6
    - future >=0.17.1
    - gitpython >=2.0.8
    - oauthlib >=2.1.0
    - packaging
    - pandas
    - pillow >=1.1.6
    - psutil
    - pyjwt
    - python >=3.6
    - requests >=2.20.0
    - requests-oauthlib >=1.0.0
    - six >=1.12.0
    - urllib3
    - websocket-client >=0.35.0
    - boto3 >=1.16.0
    - swagger-spec-validator >=2.7.4

test:
  imports:
    - neptune
    - neptune.new
    - neptune.legacy
    - neptune.management

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client
  doc_url: https://github.com/neptune-ai/neptune-client/blob/master/README.md
  dev_url: https://github.com/neptune-ai/neptune-client

extra:
  recipe-maintainers:
    - aniezurawski
    - HubertJaworski
    - pitercl
    - shnela
    - Raalsky
